name: gperks
channels:
  - conda-forge
  - defaults
dependencies:
  - importlib-metadata<4.3
  - gpytorch>=1.5,<2
  - matplotlib>=3,<4
  - numpy>=1.18,<2
  - pandas>=1.3,<2
  - pip
  - python>=3.8
  - pytorch>=1.8,<2
  - salib>=1.4.1,<2
  - scipy>=1.7,<2
  - scikit-learn>=1,<2
  - seaborn>=0.10,<1
  - torchmetrics>=0.5,<1
  - pip:
    - networkx>=2,<3
